// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNo-SCTWlR0VF82P0GEzt1tyd2L4bIVU',
    appId: '1:589550269628:web:c05e83e2fe84493c548cb9',
    messagingSenderId: '589550269628',
    projectId: 'driverspain',
    authDomain: 'driverspain.firebaseapp.com',
    storageBucket: 'driverspain.appspot.com',
    measurementId: 'G-6QHBM4V63R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBuGtq879EswO87Slb2qs2cIsZTjhQ7c',
    appId: '1:589550269628:android:1b3be8bd79ccd7cb548cb9',
    messagingSenderId: '589550269628',
    projectId: 'driverspain',
    storageBucket: 'driverspain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOCtCW6fsz2E1WLtSWPTTnwdEpjmZZuZk',
    appId: '1:589550269628:ios:8cdff0080af7c246548cb9',
    messagingSenderId: '589550269628',
    projectId: 'driverspain',
    storageBucket: 'driverspain.appspot.com',
    iosClientId: '589550269628-8ecraa7r4atgnhekgfo06ft4rdttvlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverSpainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOCtCW6fsz2E1WLtSWPTTnwdEpjmZZuZk',
    appId: '1:589550269628:ios:8cdff0080af7c246548cb9',
    messagingSenderId: '589550269628',
    projectId: 'driverspain',
    storageBucket: 'driverspain.appspot.com',
    iosClientId: '589550269628-8ecraa7r4atgnhekgfo06ft4rdttvlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverSpainApp',
  );
}
